### PR TITLE
Make contact form work with gscript

### LINKED ISSUE #29: Contact form not working
Screenshot 2020-08-10 at 8 34 20

### PR DESCRIPTION
**Pull request by mradkov**
closes #29

### CODE REVIEW

File: src/components/landing/Contact.vue [hunk 1]
```diff
@@ -57,7 +67,54 @@
...
+        'https://script.google.com/macros/s/AKfycbw9QbJ_q_ujDTaEWTwImKcqJ0QI5Agw3x7-i7TScZ1QUS080EU/exec';
+      const form = event.target.form;
+      const formData = this.getFormData(form);
+
+      const xhr = new XMLHttpRequest();
+      xhr.open('POST', url);
+      // xhr.withCredentials = true;
+      xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
+      xhr.onreadystatechange = () => {
+        xhr.readyState === 4 && xhr.status === 200 ? form.reset() : '';
```
Comment (mradkov) [inline src/components/landing/Contact.vue:108]: Maybe we would need some visual feedback for the user besides resetting the form here. 🤔

File: src/components/landing/Contact.vue [hunk 2]
```diff
@@ -57,7 +67,54 @@
...
+    },
+    submitForm(event) {
+      const url =
+        'https://script.google.com/macros/s/AKfycbw9QbJ_q_ujDTaEWTwImKcqJ0QI5Agw3x7-i7TScZ1QUS080EU/exec';
+      const form = event.target.form;
+      const formData = this.getFormData(form);
+
+      const xhr = new XMLHttpRequest();
+      xhr.open('POST', url);
+      // xhr.withCredentials = true;
```
Comment (mradkov) [inline src/components/landing/Contact.vue:105]:
```suggestion
```

This should be removed probably.

File: src/components/landing/Contact.vue [hunk 3]
```diff
@@ -57,7 +67,54 @@
...
+          p[n] = elements[n].value;
+          return p;
+        }, {}),
+        formDataNameOrder: JSON.stringify(fields),
+        formGoogleSheetName: form.dataset.sheet || 'responses',
+        formGoogleSendEmail: form.dataset.email || '',
+      };
+    },
+    submitForm(event) {
+      const url =
```
Comment (mradkov) [inline src/components/landing/Contact.vue:98]: This will be good to be extracted in some sort of config. Could be the main `gridsome.config.js`?

File: src/components/landing/Contact.vue [hunk 4]
```diff
@@ -57,7 +67,54 @@
...
+    getFormData(form) {
+      const elements = form.elements;
+      const fields = Object.keys(elements)
+        .map(k => {
+          if (elements[k].name !== undefined) {
+            return elements[k].name;
+            // special case for Edge's html collection
+          } else if (elements[k].length > 0) {
+            return elements[k].item(0).name;
+          }
```
Comment (mradkov) [inline src/components/landing/Contact.vue:81]: This can be probably simplified more.

File: src/components/landing/Contact.vue (hunk 3 above)
Comment (mradkov) [reply src/components/landing/Contact.vue:98]: Could be in `.env.`.
