### PR TITLE
Links updated

### LINKED ISSUE #28: Services menu links are broken
Services menu links should be pointed to the corresponding pages.

Screenshot 2020-08-10 at 8 33 03

### PR DESCRIPTION
**Pull request by AtanasKrondev**
Fix #28 
The current setup doesn't generate url sub-directories like
 `.../dlt-blockchain-development-services/decentralized-applications-development/`  
but just the slug
 `.../decentralized-applications-development/`
Seems fine for now, but probably if it scales will cause some duplicates.

### CODE REVIEW

File: src/components/SiteFooter.vue [hunk 1]
```diff
@@ -52,37 +52,37 @@
           <ul>
             <li>
               <a
-                href="/dlt-blockchain-development-services/blockchain-software-development/"
+                href="/blockchain-software-development/"
```
Comment (mradkov) [inline src/components/SiteFooter.vue:55]: Hmm, this will break backward compatibility with the previous links - thus breaking SEO efforts. We should keep the slugs the same way they were.

File: src/components/SiteFooter.vue [hunk 2]
```diff
@@ -52,37 +52,37 @@
...
                 title="Blockchain Development services"
               >Blockchain Development</a>
             </li>
             <li>
               <a
-                href="/dlt-blockchain-development-services/smart-contracts-development/"
+                href="/smart-contracts-development/"
```
Comment (mradkov) [inline src/components/SiteFooter.vue:61]: Same as above.

File: src/components/SiteFooter.vue [hunk 3]
```diff
@@ -52,37 +52,37 @@
...
                 title="Smart contract development services"
               >Smart Contracts</a>
             </li>
             <li>
               <a
-                href="/dlt-blockchain-development-services/smart-contract-audits/"
+                href="/smart-contract-audits/"
```
Comment (mradkov) [inline src/components/SiteFooter.vue:67]: Same as above.

File: src/components/SiteFooter.vue [hunk 4]
```diff
@@ -52,37 +52,37 @@
...
                 title="Blockchain Consulting and Advisory"
               >Smart contract Audits</a>
             </li>
             <li>
               <a
-                href="/dlt-blockchain-development-services/ico-initial-coin-offering/"
+                href="/ico-initial-coin-offering/"
```
Comment (mradkov) [inline src/components/SiteFooter.vue:73]: Same as above.

File: src/components/SiteFooter.vue [hunk 5]
```diff
@@ -52,37 +52,37 @@
...
                 title="Funrasing and crowsale"
               >Crowdsale</a>
             </li>
             <li>
               <a
-                href="/dlt-blockchain-development-services/blockchain-consulting/"
+                href="/blockchain-consulting/"
```
Comment (mradkov) [inline src/components/SiteFooter.vue:79]: Same as above.

File: src/components/SiteFooter.vue [hunk 6]
```diff
@@ -52,37 +52,37 @@
...
                 title="Blockchain Consulting and Advisory"
               >Consulting</a>
             </li>
             <li>
               <a
-                href="/dlt-blockchain-development-services/decentralized-applications-development/"
+                href="/decentralized-applications-development/"
```
Comment (mradkov) [inline src/components/SiteFooter.vue:85]: Same as above.

**Comment by mradkov** [comment]
> Fix #28
> The current setup doesn't generate url sub-directories like
> `.../dlt-blockchain-development-services/decentralized-applications-development/`
> but just the slug
> `.../decentralized-applications-development/`
> Seems fine for now, but probably if it scales will cause some duplicates.

We should keep the slugs backward compatible as it will break SEO efforts otherwise. 🤔
